CREATE TABLE IF NOT EXISTS USR( 
	USER_ID int NOT NULL PRIMARY KEY, 
	NAME varchar(100) NOT NULL,
	EMAIL varchar(100) NOT NULL,
	PASSWORD varchar(100) NOT NULL,
	USER_TYPE_CD varchar(10) NOT NULL);
	
CREATE TABLE IF NOT EXISTS BRAND(  BRAND_ID int NOT NULL PRIMARY KEY, NAME varchar(100) NOT NULL, BRAND_COLOR varchar(1) NOT NULL DEFAULT '1', LOGO_URL varchar(255), USER_ID INT NOT NULL);


CREATE TABLE IF NOT EXISTS CARD( 
	CARD_ID int NOT NULL PRIMARY KEY, 
	LEVEL INT NOT NULL,
    BRAND_ID INT NOT NULL,
    POINTS INT NOT NULL,
    VALUE VARCHAR(20) NOT NULL,
    CREDIT_PERCENTAGE  DECIMAL(2,2) NOT NULL,
    REDEMPTION_PERCENTAGE DECIMAL(2,2) NOT NULL,
    OWNER_ID INT NOT NULL);

ALTER TABLE  USR ADD INDEX user_name_btree (NAME);

ALTER TABLE BRAND ADD CONSTRAINT BRAND_USER_FK FOREIGN KEY(USER_ID)references USR(USER_ID);

ALTER TABLE CARD ADD CONSTRAINT CARD_USER_FK FOREIGN KEY(OWNER_ID)references USR(USER_ID);
ALTER TABLE CARD ADD CONSTRAINT CARD_BRAND_FK FOREIGN KEY(BRAND_ID)references BRAND(BRAND_ID);


insert into USR(USER_ID, NAME,EMAIL,PASSWORD, USER_TYPE_CD) 
	values (1, "Ivan","jaisen.95@gmail.com", "1234" ,"1");

insert into USR(USER_ID, NAME,EMAIL,PASSWORD, USER_TYPE_CD)
 values (2, "Juan", "juan@gmail.com","1234","2");

insert into BRAND(BRAND_ID, NAME, BRAND_COLOR, LOGO_URL, USER_ID)
 values (1, "Mirador","1","/assets/alpa.jpg", 2);

insert into BRAND(BRAND_ID, NAME, BRAND_COLOR, LOGO_URL, USER_ID)
 values (2, "Alpa","2","/assets/alpa.jpg", 2);

insert into BRAND(BRAND_ID, NAME, BRAND_COLOR,LOGO_URL, USER_ID)
 values(3, "Mi morena","3","/assets/alpa.jpg", 2);


insert into CARD( CARD_ID,LEVEL, POINTS,BRAND_ID,VALUE, 
				  CREDIT_PERCENTAGE, REDEMPTION_PERCENTAGE ,OWNER_ID)
values(1,1,1,1,'IMgyeryVHV',.1,.1,1);

insert into CARD( CARD_ID,LEVEL, POINTS,BRAND_ID,VALUE, 
				  CREDIT_PERCENTAGE, REDEMPTION_PERCENTAGE ,OWNER_ID)
values(2,1,2,2,'fooo33',.1,.1,1);


insert into CARD( CARD_ID,LEVEL, POINTS,BRAND_ID,VALUE, CREDIT_PERCENTAGE, REDEMPTION_PERCENTAGE ,OWNER_ID) values(3,1,1,3,'c6df7058-3ed8',.1,.1,1);


